FUNCTION(TARGET_SOURCE_TREE target)
    FILE(GLOB_RECURSE SRCS ${ARGN})
    TARGET_SOURCES(${target} PRIVATE ${SRCS})
ENDFUNCTION()

FUNCTION(TARGET_SOURCE_DIR target)
    FILE(GLOB SRCS ${ARGN})
    TARGET_SOURCES(${target} PRIVATE ${SRCS})
ENDFUNCTION()
