ADD_LIBRARY(quiver SHARED)
TARGET_SOURCE_TREE(quiver srcs/cpp/src/*.cpp)

IF(ENABLE_CUDA)
    TARGET_SOURCE_TREE(quiver srcs/cpp/src/*.cu)
    TARGET_INCLUDE_DIRECTORIES(quiver PRIVATE ${CUDA_INCLUDE_DIRS})
    TARGET_LINK_LIBRARIES(quiver ${CUDA_LIBRARIES})
    TARGET_COMPILE_OPTIONS(quiver PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--expt-extended-lambda>)
ENDIF()
