name: CI

on: [push]

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-18.04

    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    env:
      PYTHONWARNINGS: 'ignore'

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - run: pip install -U pytest
    - run: pip install -f https://download.pytorch.org/whl/torch_stable.html torch==1.6.0+cpu

    # - run: ./configure && make -j $(nproc)
    # - run: git clean -fdx

    - run: pip install --no-index .
    - run: python examples/e1.py
    - run: pytest
